import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CurrentAccountProvider } from "@/context/current_account_context";
import { FetchServerGetApiNoRediect } from "@/actions/server/fetch_server_api";
import API from "@/api/api";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function  RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await FetchServerGetApiNoRediect(API.ACCOUNT.CURRENT_ACCOUNT);
  let currentAccount:CurrentAccountResponse|null = null
  if (res && res.status === 200) {
     currentAccount = res.result;
    //  console.log("currentAccount >>> ", currentAccount)
  } 

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CurrentAccountProvider 
        currentAccountRes = {currentAccount}
        >
          {children}
        </CurrentAccountProvider>

      </body>
    </html>
  );
}
